service: sdemo-rest-api

provider:
    name: aws
    profile: anton
    role: ${opt:aws-role}
    region: ${opt:aws-region,'eu-west-1'}
    runtime: python3.7
    stage: ${opt:stage,'dev'}
    timeout: 360
    environment:
        S3_BUCKET: ${opt:s3-bucket}

functions:
  list:
    handler: item/list.list
    events:
      - http:
          path: item/
          method: get
          cors: true

  get:
    handler: item/get.get
    events:
      - http:
          path: item/{id}
          method: get
          cors: true
