service: sdemo-s3-listener

provider:
  name: aws
  role: ${opt:aws-role, 'arn:aws:iam::789525204837:role/service-role/dev-lambda'}
  region: ${opt:aws-region,'eu-west-1'}
  runtime: python3.6
  stage: ${opt:stage,'dev'}
  timeout: 360

functions:
  handle-api:
    name: ${opt:stage}-image-resize
    handler: handler.handle
    layers:
      - ${opt:arn-pillow-layer, 'arn:aws:lambda:eu-west-1:789525204837:layer:pillow:7'}
    events:
      - s3:
        existing: true
        bucket: ${opt:s3-bucket, 'sdemo-s3'}
        event: s3:ObjectCreated:*
        rules:
          - prefix: images/

    environment:
      S3_BUCKET: ${opt:s3-bucket, 'sdemo-s3'}
